// ============================================================
//  RESOURCES DATA
//  To add a resource: copy one entry block and fill in the fields.
//  Fields:
//    title       – resource name (string)
//    description – one-line summary shown on the landing page card (string)
//    thumbnail   – path to card image, relative to resources/resources.html
//                  e.g. "../images/resources/software.jpg"
//                  set to null to show a placeholder
//    page        – filename of the sub-item page, e.g. "software.html"
// ============================================================

const resourcesData = [
    {
        title: "Software",
        description: "Open-source computational tools developed by the lab for single-cell and spatial omics analysis.",
        thumbnail: null,
        page: "software.html"
    },
    {
        title: "S2GP Platform",
        description: "The Spatial and Single-Cell Genomics Platform at GIS, offering cutting-edge sequencing services.",
        thumbnail: null,
        page: "s2gp-platform.html"
    },
    {
        title: "Datasets",
        description: "Publicly available datasets generated by the lab, spanning single-cell and spatial omics studies.",
        thumbnail: null,
        page: "datasets.html"
    },
    {
        title: "Protocols",
        description: "Experimental and computational protocols used and developed by the lab.",
        thumbnail: null,
        page: "protocols.html"
    },
];